name: Daily Rebuild
run-name: "Deploy ${{ github.ref }}"
on:
  schedule:
    - cron: '0 4 * * *'
permissions:
  contents: read
jobs:
  deploy:
    name: Deploy to OCI
    runs-on: ubuntu-latest
    env:
      TF_API_TOKEN: "${{ secrets.TERRAFORM_CLOUD_TOKEN }}"
      TF_CLOUD_ORGANIZATION: "${{ github.repository_owner }}"
      TF_WORKSPACE: ${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Get latest tag
        run: echo "LATEST_TAG=$(git ls-remote --tags origin | grep -v '\^{}' | cut -d/ -f3 | sort -V | tail -n1)" >> $GITHUB_ENV
      - name: Checkout tag
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          ref: refs/tags/${{ env.LATEST_TAG }}
      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@8e08d1ba957673f5fbf971a22b3219639dc45661 # ratchet:hashicorp/tfc-workflows-github/actions/upload-configuration@v1.3.2
        id: apply-upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ./
      - name: Create Apply Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@8e08d1ba957673f5fbf971a22b3219639dc45661 # ratchet:hashicorp/tfc-workflows-github/actions/create-run@v1.3.2
        id: apply-run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.apply-upload.outputs.configuration_version_id }}
      - name: Apply
        uses: hashicorp/tfc-workflows-github/actions/apply-run@8e08d1ba957673f5fbf971a22b3219639dc45661 # ratchet:hashicorp/tfc-workflows-github/actions/apply-run@v1.3.2
        if: fromJSON(steps.apply-run.outputs.payload).data.attributes.actions.IsConfirmable
        id: apply
        with:
          run: ${{ steps.apply-run.outputs.run_id }}
          comment: "Daily rebuild of latest version run from GitHub Actions. Version deployed: ${{ env.LATEST_TAG }}"
